baseURL = "https://ggchd.fyu/"
languageCode = "en-us"
title = "log" # the title of your site

theme = "dario"

[params]
  author = "ggchd" # the author of the site
  description = "This page contains notes." # a description of your site that will be used in the meta tags

  [params.homeInfoParams]
    Title = "ggchd" # the text to display on the "/" homepage
    Content = "Jotting things down I find interesting/useful."
    Description = "A minimal web log." # The description of the home page that will be used in the open graph meta tags
